#!/usr/bin/env python3

#This program takes the .csv register maps and transcribes them into .h file(s) for use with C and microcontrollers.

import os
from typing import Union
from typing import List
import math
import csv
import shutil


#Define the file path for the input directory (contains only applicable .csv files) and the output directory (contains the .h files)
inputPath = './regMapCSV/'
outputPath = './AXX131X0X_regMaps_h/'

#Excerpt from a CSV
'''
Address,Register,NAME,Reset_Value,Start_Bit,Length
0x00,ID,RESERVED,0x2,15,4
0x00,ID,RO_CHANCNT,0x8,11,4
0x00,ID,RESERVED,0xXX,7,8
0x01,STATUS,RO_LOCK,0b0,15,1
0x01,STATUS,RO_F_RESYNC,0b0,14,1
0x01,STATUS,RO_REG_MAP,0b0,13,1
0x01,STATUS,RO_CRC_ERR,0b0,12,1
0x01,STATUS,RO_CRC_TYPE,0b0,11,1
0x01,STATUS,RO_RESET,0b1,10,1
0x01,STATUS,RO_WLENGTH,0b01,9,2
'''
 
#Get all files in the input directory
inputFiles = []
for entry in os.listdir(inputPath):
    full_path = os.path.join(inputPath, entry)
    if os.path.isfile(full_path):
        inputFiles.append(entry)

#Create a counter so we can see how many rows it iterates through
    rowCounterTotal = 0

def process_csv_file(inFile):
    """
    Processes a given .csv file and writes it to a .h file
    """

    global rowCounterTotal

    
    dataRows = []
    with open(os.path.join(inputPath, inFile), newline='') as csvfile:
        reader = csv.reader(csvfile)
        for row in reader:
            dataRows.append(row)

    #First discard the first row as it is 'Address,Register,NAME,Reset_Value,Start_Bit,Length'
    dataRows = dataRows[1:]

    #Figure out what the name of the output file should be
    outFileName = (inFile.split('.'))[0]
    outFilePath = os.path.join(outputPath,outFileName + '.h')


    #Create the output file
    with open(outFilePath, 'w') as file:
        #First, write the header and that crap
        file.write("//File: "+outFileName+'.h\n')
        file.write("//NOTE: This file was procedurally generated by the python script updateH_regMaps.py\n")
        file.write("\n")
        file.write("/*\n")
        file.write("//Address 0xXX (EXAMPLE REGISTER)\n")
        file.write("#DEFINE ADS131M08_REG_EXAMPLE 0xXX\n")
        file.write("//Define the subregisters\n")
        file.write("    //Bits 15-12 RESERVED\n")
        file.write("    //Bits 11-8 are subregister EXAMPLE_SUBREGISTER1\n")
        file.write("        #DEFINE ADS131M08_REG_EXAMPLE_SUBREGISTER1 0x00 //This is the address of the parent register\n")
        file.write("        #DEFINE ADS131M08_IDX_EXAMPLE_SUBREGISTER1 11 //This is the bitwise index at which the subregiste begins within the parent register\n")
        file.write("        #DEFINE ADS131M08_LEN_RO_CHANCNT 4 //This is how long the subregister is in bits\n")
        file.write("    //Bits 7-0 RESERVED\n")
        file.write("*/\n")
        file.write("\n")

        #Now we can work on the meat of the header file
        currAddr = 'gibberishThatWillNeverRealisticallyBeAnAddress' # Set this so to something that won't be an address so we will trigger properly on the first address
        for row in dataRows:
            rowCounterTotal -= -1
            #Check if the address has changed. If so, we're starting on a new register
            if(row[0] != currAddr):
                #The address has changed! Start a new register section.
                currAddr = row[0]
                file.write("\n")
                file.write("//Address "+row[0]+" (REGISTER "+row[1]+")\n")
                #If the register is reserved, don't create the #DEFINE
                if(row[1] != "RESERVED"):
                   file.write("#DEFINE "+outFileName+"_REG_"+row[1]+' '+row[0]+"\n")
                else:
                   file.write("//No #DEFINE for this register because it's reserved\n")                     
                file.write("//Define the subregisters\n")
                
            #Next, write the subregister entry (Different for RESERVED)
            if(row[2] == "RESERVED"):
                #If the regester is RESERVED, don't put the #DEFINE statements, but instead note in a comment that it was reserved
                #Check if the subregister is a single bit long to make comments more readable
                if(int(row[5]) == 1):
                    file.write("    //Bit "+row[4]+" RESERVED\n")
                else:
                    file.write("    //Bits "+row[4]+"-"+str(int(row[4])-int(row[5])+1)+" RESERVED\n")
            else:
                #Check if the subregister is a single bit long to make comments more readable
                if(int(row[5]) == 1):
                    file.write("    //Bit "+row[4]+" is subregister "+row[2]+"\n")
                else:
                    file.write("    //Bits "+row[4]+"-"+str(int(row[4])-int(row[5])+1)+" are subregister "+row[2]+"\n")
                file.write("        #DEFINE "+outFileName+"_REG_"+row[2]+' '+row[0]+'\n')
                file.write("        #DEFINE "+outFileName+"_IND_"+row[2]+' '+row[4]+'\n')
                file.write("        #DEFINE "+outFileName+"_LEN_"+row[2]+' '+row[5]+'\n')
        file.write("\n")
        file.write("\n")
        file.write("//End of file")
    
    pass


for csvFile in inputFiles:
    process_csv_file(csvFile)
    
print("Processed "+str(rowCounterTotal)+" rows of data")