//File: ADS131B02.h
//NOTE: This file was procedurally generated by the python script updateH_regMaps.py

/*
//Address 0xXX (EXAMPLE REGISTER)
#DEFINE ADS131M08_REG_EXAMPLE 0xXX
//Define the subregisters
    //Bits 15-12 RESERVED
    //Bits 11-8 are subregister EXAMPLE_SUBREGISTER1
        #DEFINE ADS131M08_REG_EXAMPLE_SUBREGISTER1 0x00 //This is the address of the parent register
        #DEFINE ADS131M08_IDX_EXAMPLE_SUBREGISTER1 11 //This is the bitwise index at which the subregiste begins within the parent register
        #DEFINE ADS131M08_LEN_RO_CHANCNT 4 //This is how long the subregister is in bits
    //Bits 7-0 RESERVED
*/


//Address 0x00 (REGISTER ID)
#DEFINE ADS131B02_REG_ID 0x00
//Define the subregisters
    //Bits 15-12 RESERVED
    //Bits 11-8 are subregister CHANCNT
        #DEFINE ADS131B02_REG_CHANCNT 0x00
        #DEFINE ADS131B02_IND_CHANCNT 11
        #DEFINE ADS131B02_LEN_CHANCNT 4
    //Bits 7-0 RESERVED


//End of file