//File: ADS131B04.h
//NOTE: This file was procedurally generated by the python script updateH_regMaps.py

/*
//Address 0xXX (EXAMPLE REGISTER)
#DEFINE ADS131M08_REG_EXAMPLE 0xXX
//Define the subregisters
    //Bits 15-12 RESERVED
    //Bits 11-8 are subregister EXAMPLE_SUBREGISTER1
        #DEFINE ADS131M08_REG_EXAMPLE_SUBREGISTER1 0x00 //This is the address of the parent register
        #DEFINE ADS131M08_IDX_EXAMPLE_SUBREGISTER1 11 //This is the bitwise index at which the subregiste begins within the parent register
        #DEFINE ADS131M08_LEN_RO_CHANCNT 4 //This is how long the subregister is in bits
    //Bits 7-0 RESERVED
*/


//Address 0x00 (REGISTER ID)
#DEFINE ADS131B04_REG_ID 0x00
//Define the subregisters
    //Bits 15-12 RESERVED
    //Bits 11-8 are subregister CHANCNT
        #DEFINE ADS131B04_REG_CHANCNT 0x00
        #DEFINE ADS131B04_IND_CHANCNT 11
        #DEFINE ADS131B04_LEN_CHANCNT 4
    //Bits 7-0 RESERVED

//Address 0x01 (REGISTER STATUS)
#DEFINE ADS131B04_REG_STATUS 0x01
//Define the subregisters
    //Bit 15 is subregister RO_LOCK
        #DEFINE ADS131B04_REG_RO_LOCK 0x01
        #DEFINE ADS131B04_IND_RO_LOCK 15
        #DEFINE ADS131B04_LEN_RO_LOCK 1
    //Bit 14 is subregister RO_F_RESYNC
        #DEFINE ADS131B04_REG_RO_F_RESYNC 0x01
        #DEFINE ADS131B04_IND_RO_F_RESYNC 14
        #DEFINE ADS131B04_LEN_RO_F_RESYNC 1
    //Bit 13 is subregister RO_REG_MAP
        #DEFINE ADS131B04_REG_RO_REG_MAP 0x01
        #DEFINE ADS131B04_IND_RO_REG_MAP 13
        #DEFINE ADS131B04_LEN_RO_REG_MAP 1
    //Bit 12 is subregister RO_CRC_ERR
        #DEFINE ADS131B04_REG_RO_CRC_ERR 0x01
        #DEFINE ADS131B04_IND_RO_CRC_ERR 12
        #DEFINE ADS131B04_LEN_RO_CRC_ERR 1
    //Bit 11 is subregister RO_CRC_TYPE
        #DEFINE ADS131B04_REG_RO_CRC_TYPE 0x01
        #DEFINE ADS131B04_IND_RO_CRC_TYPE 11
        #DEFINE ADS131B04_LEN_RO_CRC_TYPE 1
    //Bit 10 is subregister RO_RESET
        #DEFINE ADS131B04_REG_RO_RESET 0x01
        #DEFINE ADS131B04_IND_RO_RESET 10
        #DEFINE ADS131B04_LEN_RO_RESET 1
    //Bits 9-8 are subregister RO_WLENGTH
        #DEFINE ADS131B04_REG_RO_WLENGTH 0x01
        #DEFINE ADS131B04_IND_RO_WLENGTH 9
        #DEFINE ADS131B04_LEN_RO_WLENGTH 2
    //Bits 7-4 RESERVED
    //Bit 3 is subregister DO_DRDY3
        #DEFINE ADS131B04_REG_DO_DRDY3 0x01
        #DEFINE ADS131B04_IND_DO_DRDY3 3
        #DEFINE ADS131B04_LEN_DO_DRDY3 1
    //Bit 2 is subregister DO_DRDY2
        #DEFINE ADS131B04_REG_DO_DRDY2 0x01
        #DEFINE ADS131B04_IND_DO_DRDY2 2
        #DEFINE ADS131B04_LEN_DO_DRDY2 1
    //Bit 1 is subregister RO_DRDY1
        #DEFINE ADS131B04_REG_RO_DRDY1 0x01
        #DEFINE ADS131B04_IND_RO_DRDY1 1
        #DEFINE ADS131B04_LEN_RO_DRDY1 1
    //Bit 0 is subregister RO_DRDY0
        #DEFINE ADS131B04_REG_RO_DRDY0 0x01
        #DEFINE ADS131B04_IND_RO_DRDY0 0
        #DEFINE ADS131B04_LEN_RO_DRDY0 1

//Address 0x02 (REGISTER MODE)
#DEFINE ADS131B04_REG_MODE 0x02
//Define the subregisters
    //Bits 15-14 RESERVED
    //Bit 13 is subregister REGCRC_EN
        #DEFINE ADS131B04_REG_REGCRC_EN 0x02
        #DEFINE ADS131B04_IND_REGCRC_EN 13
        #DEFINE ADS131B04_LEN_REGCRC_EN 1
    //Bit 12 is subregister RX_CRC_EN
        #DEFINE ADS131B04_REG_RX_CRC_EN 0x02
        #DEFINE ADS131B04_IND_RX_CRC_EN 12
        #DEFINE ADS131B04_LEN_RX_CRC_EN 1
    //Bit 11 is subregister CRC_TYPE
        #DEFINE ADS131B04_REG_CRC_TYPE 0x02
        #DEFINE ADS131B04_IND_CRC_TYPE 11
        #DEFINE ADS131B04_LEN_CRC_TYPE 1
    //Bit 10 is subregister RESET
        #DEFINE ADS131B04_REG_RESET 0x02
        #DEFINE ADS131B04_IND_RESET 10
        #DEFINE ADS131B04_LEN_RESET 1
    //Bits 9-8 are subregister WLENGTH
        #DEFINE ADS131B04_REG_WLENGTH 0x02
        #DEFINE ADS131B04_IND_WLENGTH 9
        #DEFINE ADS131B04_LEN_WLENGTH 2
    //Bits 7-5 RESERVED
    //Bit 4 is subregister TIMEOUT
        #DEFINE ADS131B04_REG_TIMEOUT 0x02
        #DEFINE ADS131B04_IND_TIMEOUT 4
        #DEFINE ADS131B04_LEN_TIMEOUT 1
    //Bits 3-2 are subregister DRDY_SEL
        #DEFINE ADS131B04_REG_DRDY_SEL 0x02
        #DEFINE ADS131B04_IND_DRDY_SEL 3
        #DEFINE ADS131B04_LEN_DRDY_SEL 2
    //Bit 1 is subregister DRDY_HIZ
        #DEFINE ADS131B04_REG_DRDY_HIZ 0x02
        #DEFINE ADS131B04_IND_DRDY_HIZ 1
        #DEFINE ADS131B04_LEN_DRDY_HIZ 1
    //Bit 0 is subregister DRDY_FMT
        #DEFINE ADS131B04_REG_DRDY_FMT 0x02
        #DEFINE ADS131B04_IND_DRDY_FMT 0
        #DEFINE ADS131B04_LEN_DRDY_FMT 1

//Address 0x03 (REGISTER CLOCK)
#DEFINE ADS131B04_REG_CLOCK 0x03
//Define the subregisters
    //Bits 15-12 RESERVED
    //Bit 11 is subregister CH3_EN
        #DEFINE ADS131B04_REG_CH3_EN 0x03
        #DEFINE ADS131B04_IND_CH3_EN 11
        #DEFINE ADS131B04_LEN_CH3_EN 1
    //Bit 10 is subregister CH2_EN
        #DEFINE ADS131B04_REG_CH2_EN 0x03
        #DEFINE ADS131B04_IND_CH2_EN 10
        #DEFINE ADS131B04_LEN_CH2_EN 1
    //Bit 9 is subregister CH1_EN
        #DEFINE ADS131B04_REG_CH1_EN 0x03
        #DEFINE ADS131B04_IND_CH1_EN 9
        #DEFINE ADS131B04_LEN_CH1_EN 1
    //Bit 8 is subregister CH0_EN
        #DEFINE ADS131B04_REG_CH0_EN 0x03
        #DEFINE ADS131B04_IND_CH0_EN 8
        #DEFINE ADS131B04_LEN_CH0_EN 1
    //Bit 7 is subregister CLK_SEL
        #DEFINE ADS131B04_REG_CLK_SEL 0x03
        #DEFINE ADS131B04_IND_CLK_SEL 7
        #DEFINE ADS131B04_LEN_CLK_SEL 1
    //Bits 6-5 RESERVED
    //Bits 4-2 are subregister OSR
        #DEFINE ADS131B04_REG_OSR 0x03
        #DEFINE ADS131B04_IND_OSR 4
        #DEFINE ADS131B04_LEN_OSR 3
    //Bits 1-0 are subregister PWR
        #DEFINE ADS131B04_REG_PWR 0x03
        #DEFINE ADS131B04_IND_PWR 1
        #DEFINE ADS131B04_LEN_PWR 2

//Address 0x04 (REGISTER GAIN1)
#DEFINE ADS131B04_REG_GAIN1 0x04
//Define the subregisters
    //Bit 15 RESERVED
    //Bits 14-12 are subregister PGAGAIN3
        #DEFINE ADS131B04_REG_PGAGAIN3 0x04
        #DEFINE ADS131B04_IND_PGAGAIN3 14
        #DEFINE ADS131B04_LEN_PGAGAIN3 3
    //Bit 11 RESERVED
    //Bits 10-8 are subregister PGAGAIN2
        #DEFINE ADS131B04_REG_PGAGAIN2 0x04
        #DEFINE ADS131B04_IND_PGAGAIN2 10
        #DEFINE ADS131B04_LEN_PGAGAIN2 3
    //Bit 7 RESERVED
    //Bits 6-4 are subregister PGAGAIN1
        #DEFINE ADS131B04_REG_PGAGAIN1 0x04
        #DEFINE ADS131B04_IND_PGAGAIN1 6
        #DEFINE ADS131B04_LEN_PGAGAIN1 3
    //Bit 3 RESERVED
    //Bits 2-0 are subregister PGAGAIN0
        #DEFINE ADS131B04_REG_PGAGAIN0 0x04
        #DEFINE ADS131B04_IND_PGAGAIN0 2
        #DEFINE ADS131B04_LEN_PGAGAIN0 3

//Address 0x05 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x06 (REGISTER GLOBAL_CHOP_CFG)
#DEFINE ADS131B04_REG_GLOBAL_CHOP_CFG 0x06
//Define the subregisters
    //Bits 15-13 RESERVED
    //Bits 12-9 are subregister GC_DLY
        #DEFINE ADS131B04_REG_GC_DLY 0x06
        #DEFINE ADS131B04_IND_GC_DLY 12
        #DEFINE ADS131B04_LEN_GC_DLY 4
    //Bit 8 is subregister GC_EN
        #DEFINE ADS131B04_REG_GC_EN 0x06
        #DEFINE ADS131B04_IND_GC_EN 8
        #DEFINE ADS131B04_LEN_GC_EN 1
    //Bits 7-0 RESERVED

//Address 0x07 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x08 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x09 (REGISTER CH0_CHG)
#DEFINE ADS131B04_REG_CH0_CHG 0x09
//Define the subregisters
    //Bits 15-2 RESERVED
    //Bits 1-0 are subregister MUX0
        #DEFINE ADS131B04_REG_MUX0 0x09
        #DEFINE ADS131B04_IND_MUX0 1
        #DEFINE ADS131B04_LEN_MUX0 2

//Address 0x0A (REGISTER CH0_OCAL_MSB)
#DEFINE ADS131B04_REG_CH0_OCAL_MSB 0x0A
//Define the subregisters
    //Bits 15-0 are subregister OCAL0_MSB
        #DEFINE ADS131B04_REG_OCAL0_MSB 0x0A
        #DEFINE ADS131B04_IND_OCAL0_MSB 15
        #DEFINE ADS131B04_LEN_OCAL0_MSB 16

//Address 0x0B (REGISTER CH0_OCAL_LSB)
#DEFINE ADS131B04_REG_CH0_OCAL_LSB 0x0B
//Define the subregisters
    //Bits 15-8 are subregister OCAL0_LSB
        #DEFINE ADS131B04_REG_OCAL0_LSB 0x0B
        #DEFINE ADS131B04_IND_OCAL0_LSB 15
        #DEFINE ADS131B04_LEN_OCAL0_LSB 8
    //Bits 7-0 RESERVED

//Address 0x0C (REGISTER CH0_GCAL_MSB)
#DEFINE ADS131B04_REG_CH0_GCAL_MSB 0x0C
//Define the subregisters
    //Bits 15-0 are subregister GCAL0_MSB
        #DEFINE ADS131B04_REG_GCAL0_MSB 0x0C
        #DEFINE ADS131B04_IND_GCAL0_MSB 15
        #DEFINE ADS131B04_LEN_GCAL0_MSB 16

//Address 0x0D (REGISTER CH0_GCAL_LSB)
#DEFINE ADS131B04_REG_CH0_GCAL_LSB 0x0D
//Define the subregisters
    //Bits 15-8 are subregister GCAL0_LSB
        #DEFINE ADS131B04_REG_GCAL0_LSB 0x0D
        #DEFINE ADS131B04_IND_GCAL0_LSB 15
        #DEFINE ADS131B04_LEN_GCAL0_LSB 8
    //Bits 7-0 RESERVED

//Address 0x0E (REGISTER CH1_CHG)
#DEFINE ADS131B04_REG_CH1_CHG 0x0E
//Define the subregisters
    //Bits 15-2 RESERVED
    //Bits 1-0 are subregister MUX1
        #DEFINE ADS131B04_REG_MUX1 0x0E
        #DEFINE ADS131B04_IND_MUX1 1
        #DEFINE ADS131B04_LEN_MUX1 2

//Address 0x0F (REGISTER CH1_OCAL_MSB)
#DEFINE ADS131B04_REG_CH1_OCAL_MSB 0x0F
//Define the subregisters
    //Bits 15-0 are subregister OCAL1_MSB
        #DEFINE ADS131B04_REG_OCAL1_MSB 0x0F
        #DEFINE ADS131B04_IND_OCAL1_MSB 15
        #DEFINE ADS131B04_LEN_OCAL1_MSB 16

//Address 0x10 (REGISTER CH1_OCAL_LSB)
#DEFINE ADS131B04_REG_CH1_OCAL_LSB 0x10
//Define the subregisters
    //Bits 15-8 are subregister OCAL1_LSB
        #DEFINE ADS131B04_REG_OCAL1_LSB 0x10
        #DEFINE ADS131B04_IND_OCAL1_LSB 15
        #DEFINE ADS131B04_LEN_OCAL1_LSB 8
    //Bits 7-0 RESERVED

//Address 0x11 (REGISTER CH1_GCAL_MSB)
#DEFINE ADS131B04_REG_CH1_GCAL_MSB 0x11
//Define the subregisters
    //Bits 15-0 are subregister GCAL1_MSB
        #DEFINE ADS131B04_REG_GCAL1_MSB 0x11
        #DEFINE ADS131B04_IND_GCAL1_MSB 15
        #DEFINE ADS131B04_LEN_GCAL1_MSB 16

//Address 0x12 (REGISTER CH1_GCAL_LSB)
#DEFINE ADS131B04_REG_CH1_GCAL_LSB 0x12
//Define the subregisters
    //Bits 15-8 are subregister GCAL1_LSB
        #DEFINE ADS131B04_REG_GCAL1_LSB 0x12
        #DEFINE ADS131B04_IND_GCAL1_LSB 15
        #DEFINE ADS131B04_LEN_GCAL1_LSB 8
    //Bits 7-0 RESERVED

//Address 0x13 (REGISTER CH2_CHG)
#DEFINE ADS131B04_REG_CH2_CHG 0x13
//Define the subregisters
    //Bits 15-2 RESERVED
    //Bits 1-0 are subregister MUX2
        #DEFINE ADS131B04_REG_MUX2 0x13
        #DEFINE ADS131B04_IND_MUX2 1
        #DEFINE ADS131B04_LEN_MUX2 2

//Address 0x14 (REGISTER CH2_OCAL_MSB)
#DEFINE ADS131B04_REG_CH2_OCAL_MSB 0x14
//Define the subregisters
    //Bits 15-0 are subregister OCAL2_MSB
        #DEFINE ADS131B04_REG_OCAL2_MSB 0x14
        #DEFINE ADS131B04_IND_OCAL2_MSB 15
        #DEFINE ADS131B04_LEN_OCAL2_MSB 16

//Address 0x15 (REGISTER CH2_OCAL_LSB)
#DEFINE ADS131B04_REG_CH2_OCAL_LSB 0x15
//Define the subregisters
    //Bits 15-8 are subregister OCAL2_LSB
        #DEFINE ADS131B04_REG_OCAL2_LSB 0x15
        #DEFINE ADS131B04_IND_OCAL2_LSB 15
        #DEFINE ADS131B04_LEN_OCAL2_LSB 8
    //Bits 7-0 RESERVED

//Address 0x16 (REGISTER CH2_GCAL_MSB)
#DEFINE ADS131B04_REG_CH2_GCAL_MSB 0x16
//Define the subregisters
    //Bits 15-0 are subregister GCAL2_MSB
        #DEFINE ADS131B04_REG_GCAL2_MSB 0x16
        #DEFINE ADS131B04_IND_GCAL2_MSB 15
        #DEFINE ADS131B04_LEN_GCAL2_MSB 16

//Address 0x17 (REGISTER CH2_GCAL_LSB)
#DEFINE ADS131B04_REG_CH2_GCAL_LSB 0x17
//Define the subregisters
    //Bits 15-8 are subregister GCAL2_LSB
        #DEFINE ADS131B04_REG_GCAL2_LSB 0x17
        #DEFINE ADS131B04_IND_GCAL2_LSB 15
        #DEFINE ADS131B04_LEN_GCAL2_LSB 8
    //Bits 7-0 RESERVED

//Address 0x18 (REGISTER CH3_CHG)
#DEFINE ADS131B04_REG_CH3_CHG 0x18
//Define the subregisters
    //Bits 15-2 RESERVED
    //Bits 1-0 are subregister MUX3
        #DEFINE ADS131B04_REG_MUX3 0x18
        #DEFINE ADS131B04_IND_MUX3 1
        #DEFINE ADS131B04_LEN_MUX3 2

//Address 0x19 (REGISTER CH3_OCAL_MSB)
#DEFINE ADS131B04_REG_CH3_OCAL_MSB 0x19
//Define the subregisters
    //Bits 15-0 are subregister OCAL3_MSB
        #DEFINE ADS131B04_REG_OCAL3_MSB 0x19
        #DEFINE ADS131B04_IND_OCAL3_MSB 15
        #DEFINE ADS131B04_LEN_OCAL3_MSB 16

//Address 0x1A (REGISTER CH3_OCAL_LSB)
#DEFINE ADS131B04_REG_CH3_OCAL_LSB 0x1A
//Define the subregisters
    //Bits 15-8 are subregister OCAL3_LSB
        #DEFINE ADS131B04_REG_OCAL3_LSB 0x1A
        #DEFINE ADS131B04_IND_OCAL3_LSB 15
        #DEFINE ADS131B04_LEN_OCAL3_LSB 8
    //Bits 7-0 RESERVED

//Address 0x1B (REGISTER CH3_GCAL_MSB)
#DEFINE ADS131B04_REG_CH3_GCAL_MSB 0x1B
//Define the subregisters
    //Bits 15-0 are subregister GCAL3_MSB
        #DEFINE ADS131B04_REG_GCAL3_MSB 0x1B
        #DEFINE ADS131B04_IND_GCAL3_MSB 15
        #DEFINE ADS131B04_LEN_GCAL3_MSB 16

//Address 0x1C (REGISTER CH3_GCAL_LSB)
#DEFINE ADS131B04_REG_CH3_GCAL_LSB 0x1C
//Define the subregisters
    //Bits 15-8 are subregister GCAL3_LSB
        #DEFINE ADS131B04_REG_GCAL3_LSB 0x1C
        #DEFINE ADS131B04_IND_GCAL3_LSB 15
        #DEFINE ADS131B04_LEN_GCAL3_LSB 8
    //Bits 7-0 RESERVED

//Address 0x1D (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x1E (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x1F (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x20 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x21 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x22 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x23 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x24 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x25 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x26 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x27 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x28 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x29 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2A (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2B (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2C (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2D (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2E (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2F (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x30 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x31 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x32 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x33 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x34 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x35 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x36 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x37 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x38 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x39 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3A (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3B (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3C (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3D (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3E (REGISTER REGMAP_CRC)
#DEFINE ADS131B04_REG_REGMAP_CRC 0x3E
//Define the subregisters
    //Bits 15-0 are subregister REG_CRC
        #DEFINE ADS131B04_REG_REG_CRC 0x3E
        #DEFINE ADS131B04_IND_REG_CRC 15
        #DEFINE ADS131B04_LEN_REG_CRC 16

//Address 0x3F (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED


//End of file