//File: AMC131M03.h
//NOTE: This file was procedurally generated by the python script updateH_regMaps.py

/*
//Address 0xXX (EXAMPLE REGISTER)
#DEFINE ADS131M08_REG_EXAMPLE 0xXX
//Define the subregisters
    //Bits 15-12 RESERVED
    //Bits 11-8 are subregister EXAMPLE_SUBREGISTER1
        #DEFINE ADS131M08_REG_EXAMPLE_SUBREGISTER1 0x00 //This is the address of the parent register
        #DEFINE ADS131M08_IDX_EXAMPLE_SUBREGISTER1 11 //This is the bitwise index at which the subregiste begins within the parent register
        #DEFINE ADS131M08_LEN_RO_CHANCNT 4 //This is how long the subregister is in bits
    //Bits 7-0 RESERVED
*/


//Address 0x00 (REGISTER ID)
#DEFINE AMC131M03_REG_ID 0x00
//Define the subregisters
    //Bits 15-12 RESERVED
    //Bits 11-8 are subregister CHANCNT
        #DEFINE AMC131M03_REG_CHANCNT 0x00
        #DEFINE AMC131M03_IND_CHANCNT 11
        #DEFINE AMC131M03_LEN_CHANCNT 4
    //Bits 7-0 RESERVED

//Address 0x01 (REGISTER STATUS)
#DEFINE AMC131M03_REG_STATUS 0x01
//Define the subregisters
    //Bit 15 is subregister RO_LOCK
        #DEFINE AMC131M03_REG_RO_LOCK 0x01
        #DEFINE AMC131M03_IND_RO_LOCK 15
        #DEFINE AMC131M03_LEN_RO_LOCK 1
    //Bit 14 is subregister RO_F_RESYNC
        #DEFINE AMC131M03_REG_RO_F_RESYNC 0x01
        #DEFINE AMC131M03_IND_RO_F_RESYNC 14
        #DEFINE AMC131M03_LEN_RO_F_RESYNC 1
    //Bit 13 is subregister RO_REG_MAP
        #DEFINE AMC131M03_REG_RO_REG_MAP 0x01
        #DEFINE AMC131M03_IND_RO_REG_MAP 13
        #DEFINE AMC131M03_LEN_RO_REG_MAP 1
    //Bit 12 is subregister RO_CRC_ERR
        #DEFINE AMC131M03_REG_RO_CRC_ERR 0x01
        #DEFINE AMC131M03_IND_RO_CRC_ERR 12
        #DEFINE AMC131M03_LEN_RO_CRC_ERR 1
    //Bit 11 is subregister RO_CRC_TYPE
        #DEFINE AMC131M03_REG_RO_CRC_TYPE 0x01
        #DEFINE AMC131M03_IND_RO_CRC_TYPE 11
        #DEFINE AMC131M03_LEN_RO_CRC_TYPE 1
    //Bit 10 is subregister RO_RESET
        #DEFINE AMC131M03_REG_RO_RESET 0x01
        #DEFINE AMC131M03_IND_RO_RESET 10
        #DEFINE AMC131M03_LEN_RO_RESET 1
    //Bits 9-8 are subregister RO_WLENGTH
        #DEFINE AMC131M03_REG_RO_WLENGTH 0x01
        #DEFINE AMC131M03_IND_RO_WLENGTH 9
        #DEFINE AMC131M03_LEN_RO_WLENGTH 2
    //Bit 7 is subregister RO_FUSE_FAIL
        #DEFINE AMC131M03_REG_RO_FUSE_FAIL 0x01
        #DEFINE AMC131M03_IND_RO_FUSE_FAIL 7
        #DEFINE AMC131M03_LEN_RO_FUSE_FAIL 1
    //Bit 6 is subregister RO_SEC_FAIL
        #DEFINE AMC131M03_REG_RO_SEC_FAIL 0x01
        #DEFINE AMC131M03_IND_RO_SEC_FAIL 6
        #DEFINE AMC131M03_LEN_RO_SEC_FAIL 1
    //Bits 5-3 RESERVED
    //Bit 2 is subregister RO_DRDY2
        #DEFINE AMC131M03_REG_RO_DRDY2 0x01
        #DEFINE AMC131M03_IND_RO_DRDY2 2
        #DEFINE AMC131M03_LEN_RO_DRDY2 1
    //Bit 1 is subregister RO_DRDY1
        #DEFINE AMC131M03_REG_RO_DRDY1 0x01
        #DEFINE AMC131M03_IND_RO_DRDY1 1
        #DEFINE AMC131M03_LEN_RO_DRDY1 1
    //Bit 0 is subregister RO_DRDY0
        #DEFINE AMC131M03_REG_RO_DRDY0 0x01
        #DEFINE AMC131M03_IND_RO_DRDY0 0
        #DEFINE AMC131M03_LEN_RO_DRDY0 1

//Address 0x02 (REGISTER MODE)
#DEFINE AMC131M03_REG_MODE 0x02
//Define the subregisters
    //Bits 15-14 RESERVED
    //Bit 13 is subregister REG_CRC_EN
        #DEFINE AMC131M03_REG_REG_CRC_EN 0x02
        #DEFINE AMC131M03_IND_REG_CRC_EN 13
        #DEFINE AMC131M03_LEN_REG_CRC_EN 1
    //Bit 12 is subregister RX_CRC_EN
        #DEFINE AMC131M03_REG_RX_CRC_EN 0x02
        #DEFINE AMC131M03_IND_RX_CRC_EN 12
        #DEFINE AMC131M03_LEN_RX_CRC_EN 1
    //Bit 11 is subregister CRC_TYPE
        #DEFINE AMC131M03_REG_CRC_TYPE 0x02
        #DEFINE AMC131M03_IND_CRC_TYPE 11
        #DEFINE AMC131M03_LEN_CRC_TYPE 1
    //Bit 10 is subregister RESET
        #DEFINE AMC131M03_REG_RESET 0x02
        #DEFINE AMC131M03_IND_RESET 10
        #DEFINE AMC131M03_LEN_RESET 1
    //Bits 9-8 are subregister WLENGTH
        #DEFINE AMC131M03_REG_WLENGTH 0x02
        #DEFINE AMC131M03_IND_WLENGTH 9
        #DEFINE AMC131M03_LEN_WLENGTH 2
    //Bits 7-5 RESERVED
    //Bit 4 is subregister TIMEOUT
        #DEFINE AMC131M03_REG_TIMEOUT 0x02
        #DEFINE AMC131M03_IND_TIMEOUT 4
        #DEFINE AMC131M03_LEN_TIMEOUT 1
    //Bits 3-2 are subregister DRDY_SEL
        #DEFINE AMC131M03_REG_DRDY_SEL 0x02
        #DEFINE AMC131M03_IND_DRDY_SEL 3
        #DEFINE AMC131M03_LEN_DRDY_SEL 2
    //Bit 1 is subregister DRDY_HIZ
        #DEFINE AMC131M03_REG_DRDY_HIZ 0x02
        #DEFINE AMC131M03_IND_DRDY_HIZ 1
        #DEFINE AMC131M03_LEN_DRDY_HIZ 1
    //Bit 0 is subregister DRDY_FMT
        #DEFINE AMC131M03_REG_DRDY_FMT 0x02
        #DEFINE AMC131M03_IND_DRDY_FMT 0
        #DEFINE AMC131M03_LEN_DRDY_FMT 1

//Address 0x03 (REGISTER CLOCK)
#DEFINE AMC131M03_REG_CLOCK 0x03
//Define the subregisters
    //Bits 15-11 RESERVED
    //Bit 10 is subregister CH2_EN
        #DEFINE AMC131M03_REG_CH2_EN 0x03
        #DEFINE AMC131M03_IND_CH2_EN 10
        #DEFINE AMC131M03_LEN_CH2_EN 1
    //Bit 9 is subregister CH1_EN
        #DEFINE AMC131M03_REG_CH1_EN 0x03
        #DEFINE AMC131M03_IND_CH1_EN 9
        #DEFINE AMC131M03_LEN_CH1_EN 1
    //Bit 8 is subregister CH0_EN
        #DEFINE AMC131M03_REG_CH0_EN 0x03
        #DEFINE AMC131M03_IND_CH0_EN 8
        #DEFINE AMC131M03_LEN_CH0_EN 1
    //Bits 7-6 are subregister CLK_DIV
        #DEFINE AMC131M03_REG_CLK_DIV 0x03
        #DEFINE AMC131M03_IND_CLK_DIV 7
        #DEFINE AMC131M03_LEN_CLK_DIV 2
    //Bit 5 is subregister TURBO
        #DEFINE AMC131M03_REG_TURBO 0x03
        #DEFINE AMC131M03_IND_TURBO 5
        #DEFINE AMC131M03_LEN_TURBO 1
    //Bits 4-2 are subregister OSR
        #DEFINE AMC131M03_REG_OSR 0x03
        #DEFINE AMC131M03_IND_OSR 4
        #DEFINE AMC131M03_LEN_OSR 3
    //Bits 1-0 are subregister PWR
        #DEFINE AMC131M03_REG_PWR 0x03
        #DEFINE AMC131M03_IND_PWR 1
        #DEFINE AMC131M03_LEN_PWR 2

//Address 0x04 (REGISTER GAIN)
#DEFINE AMC131M03_REG_GAIN 0x04
//Define the subregisters
    //Bits 15-11 RESERVED
    //Bits 10-8 are subregister PGAGAIN2
        #DEFINE AMC131M03_REG_PGAGAIN2 0x04
        #DEFINE AMC131M03_IND_PGAGAIN2 10
        #DEFINE AMC131M03_LEN_PGAGAIN2 3
    //Bit 7 RESERVED
    //Bits 6-4 are subregister PGAGAIN1
        #DEFINE AMC131M03_REG_PGAGAIN1 0x04
        #DEFINE AMC131M03_IND_PGAGAIN1 6
        #DEFINE AMC131M03_LEN_PGAGAIN1 3
    //Bit 3 RESERVED
    //Bits 2-0 are subregister PGAGAIN0
        #DEFINE AMC131M03_REG_PGAGAIN0 0x04
        #DEFINE AMC131M03_IND_PGAGAIN0 2
        #DEFINE AMC131M03_LEN_PGAGAIN0 3

//Address 0x05 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x06 (REGISTER CFG)
#DEFINE AMC131M03_REG_CFG 0x06
//Define the subregisters
    //Bit 15 RESERVED
    //Bit 14 is subregister GPO_EN
        #DEFINE AMC131M03_REG_GPO_EN 0x06
        #DEFINE AMC131M03_IND_GPO_EN 14
        #DEFINE AMC131M03_LEN_GPO_EN 1
    //Bit 13 is subregister GPO_DAT
        #DEFINE AMC131M03_REG_GPO_DAT 0x06
        #DEFINE AMC131M03_IND_GPO_DAT 13
        #DEFINE AMC131M03_LEN_GPO_DAT 1
    //Bits 12-9 are subregister GC_DLY
        #DEFINE AMC131M03_REG_GC_DLY 0x06
        #DEFINE AMC131M03_IND_GC_DLY 12
        #DEFINE AMC131M03_LEN_GC_DLY 4
    //Bit 8 is subregister GC_EN
        #DEFINE AMC131M03_REG_GC_EN 0x06
        #DEFINE AMC131M03_IND_GC_EN 8
        #DEFINE AMC131M03_LEN_GC_EN 1
    //Bits 7-0 RESERVED

//Address 0x07 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x08 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x09 (REGISTER CH0_CFG)
#DEFINE AMC131M03_REG_CH0_CFG 0x09
//Define the subregisters
    //Bits 15-6 are subregister PHASE0
        #DEFINE AMC131M03_REG_PHASE0 0x09
        #DEFINE AMC131M03_IND_PHASE0 15
        #DEFINE AMC131M03_LEN_PHASE0 10
    //Bits 5-2 RESERVED
    //Bits 1-0 are subregister MUX0
        #DEFINE AMC131M03_REG_MUX0 0x09
        #DEFINE AMC131M03_IND_MUX0 1
        #DEFINE AMC131M03_LEN_MUX0 2

//Address 0x0A (REGISTER CH0_OCAL_MSB)
#DEFINE AMC131M03_REG_CH0_OCAL_MSB 0x0A
//Define the subregisters
    //Bits 15-0 are subregister OCAL0_MSB
        #DEFINE AMC131M03_REG_OCAL0_MSB 0x0A
        #DEFINE AMC131M03_IND_OCAL0_MSB 15
        #DEFINE AMC131M03_LEN_OCAL0_MSB 16

//Address 0x0B (REGISTER CH0_OCAL_LSB)
#DEFINE AMC131M03_REG_CH0_OCAL_LSB 0x0B
//Define the subregisters
    //Bits 15-8 are subregister OCAL0_LSB
        #DEFINE AMC131M03_REG_OCAL0_LSB 0x0B
        #DEFINE AMC131M03_IND_OCAL0_LSB 15
        #DEFINE AMC131M03_LEN_OCAL0_LSB 8
    //Bits 7-0 RESERVED

//Address 0x0C (REGISTER CH0_GCAL_MSB)
#DEFINE AMC131M03_REG_CH0_GCAL_MSB 0x0C
//Define the subregisters
    //Bits 15-0 are subregister GCAL0_MSB
        #DEFINE AMC131M03_REG_GCAL0_MSB 0x0C
        #DEFINE AMC131M03_IND_GCAL0_MSB 15
        #DEFINE AMC131M03_LEN_GCAL0_MSB 16

//Address 0x0D (REGISTER CH0_GCAL_LSB)
#DEFINE AMC131M03_REG_CH0_GCAL_LSB 0x0D
//Define the subregisters
    //Bits 15-8 are subregister GCAL0_LSB
        #DEFINE AMC131M03_REG_GCAL0_LSB 0x0D
        #DEFINE AMC131M03_IND_GCAL0_LSB 15
        #DEFINE AMC131M03_LEN_GCAL0_LSB 8
    //Bits 7-0 RESERVED

//Address 0x0E (REGISTER CH1_CFG)
#DEFINE AMC131M03_REG_CH1_CFG 0x0E
//Define the subregisters
    //Bits 15-6 are subregister PHASE1
        #DEFINE AMC131M03_REG_PHASE1 0x0E
        #DEFINE AMC131M03_IND_PHASE1 15
        #DEFINE AMC131M03_LEN_PHASE1 10
    //Bits 5-2 RESERVED
    //Bits 1-0 are subregister MUX1
        #DEFINE AMC131M03_REG_MUX1 0x0E
        #DEFINE AMC131M03_IND_MUX1 1
        #DEFINE AMC131M03_LEN_MUX1 2

//Address 0x0F (REGISTER CH1_OCAL_MSB)
#DEFINE AMC131M03_REG_CH1_OCAL_MSB 0x0F
//Define the subregisters
    //Bits 15-0 are subregister OCAL1_MSB
        #DEFINE AMC131M03_REG_OCAL1_MSB 0x0F
        #DEFINE AMC131M03_IND_OCAL1_MSB 15
        #DEFINE AMC131M03_LEN_OCAL1_MSB 16

//Address 0x10 (REGISTER CH1_OCAL_LSB)
#DEFINE AMC131M03_REG_CH1_OCAL_LSB 0x10
//Define the subregisters
    //Bits 15-8 are subregister OCAL1_LSB
        #DEFINE AMC131M03_REG_OCAL1_LSB 0x10
        #DEFINE AMC131M03_IND_OCAL1_LSB 15
        #DEFINE AMC131M03_LEN_OCAL1_LSB 8
    //Bits 7-0 RESERVED

//Address 0x11 (REGISTER CH1_GCAL_MSB)
#DEFINE AMC131M03_REG_CH1_GCAL_MSB 0x11
//Define the subregisters
    //Bits 15-0 are subregister GCAL1_MSB
        #DEFINE AMC131M03_REG_GCAL1_MSB 0x11
        #DEFINE AMC131M03_IND_GCAL1_MSB 15
        #DEFINE AMC131M03_LEN_GCAL1_MSB 16

//Address 0x12 (REGISTER CH1_GCAL_LSB)
#DEFINE AMC131M03_REG_CH1_GCAL_LSB 0x12
//Define the subregisters
    //Bits 15-8 are subregister GCAL1_LSB
        #DEFINE AMC131M03_REG_GCAL1_LSB 0x12
        #DEFINE AMC131M03_IND_GCAL1_LSB 15
        #DEFINE AMC131M03_LEN_GCAL1_LSB 8
    //Bits 7-0 RESERVED

//Address 0x13 (REGISTER CH2_CFG)
#DEFINE AMC131M03_REG_CH2_CFG 0x13
//Define the subregisters
    //Bits 15-6 are subregister PHASE2
        #DEFINE AMC131M03_REG_PHASE2 0x13
        #DEFINE AMC131M03_IND_PHASE2 15
        #DEFINE AMC131M03_LEN_PHASE2 10
    //Bits 5-2 RESERVED
    //Bits 1-0 are subregister MUX2
        #DEFINE AMC131M03_REG_MUX2 0x13
        #DEFINE AMC131M03_IND_MUX2 1
        #DEFINE AMC131M03_LEN_MUX2 2

//Address 0x14 (REGISTER CH2_OCAL_MSB)
#DEFINE AMC131M03_REG_CH2_OCAL_MSB 0x14
//Define the subregisters
    //Bits 15-0 are subregister OCAL2_MSB
        #DEFINE AMC131M03_REG_OCAL2_MSB 0x14
        #DEFINE AMC131M03_IND_OCAL2_MSB 15
        #DEFINE AMC131M03_LEN_OCAL2_MSB 16

//Address 0x15 (REGISTER CH2_OCAL_LSB)
#DEFINE AMC131M03_REG_CH2_OCAL_LSB 0x15
//Define the subregisters
    //Bits 15-8 are subregister OCAL2_LSB
        #DEFINE AMC131M03_REG_OCAL2_LSB 0x15
        #DEFINE AMC131M03_IND_OCAL2_LSB 15
        #DEFINE AMC131M03_LEN_OCAL2_LSB 8
    //Bits 7-0 RESERVED

//Address 0x16 (REGISTER CH2_GCAL_MSB)
#DEFINE AMC131M03_REG_CH2_GCAL_MSB 0x16
//Define the subregisters
    //Bits 15-0 are subregister GCAL2_MSB
        #DEFINE AMC131M03_REG_GCAL2_MSB 0x16
        #DEFINE AMC131M03_IND_GCAL2_MSB 15
        #DEFINE AMC131M03_LEN_GCAL2_MSB 16

//Address 0x17 (REGISTER CH2_GCAL_LSB)
#DEFINE AMC131M03_REG_CH2_GCAL_LSB 0x17
//Define the subregisters
    //Bits 15-8 are subregister GCAL2_LSB
        #DEFINE AMC131M03_REG_GCAL2_LSB 0x17
        #DEFINE AMC131M03_IND_GCAL2_LSB 15
        #DEFINE AMC131M03_LEN_GCAL2_LSB 8
    //Bits 7-0 RESERVED

//Address 0x18 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x19 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x1A (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x1B (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x1C (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x1D (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x1E (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x1F (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x20 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x21 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x22 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x23 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x24 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x25 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x26 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x27 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x28 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x29 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2A (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2B (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2C (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2D (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2E (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x2F (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x30 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x31 (REGISTER DCDC_CTRL)
#DEFINE AMC131M03_REG_DCDC_CTRL 0x31
//Define the subregisters
    //Bits 15-12 RESERVED
    //Bits 11-8 are subregister DCDC_FREQ
        #DEFINE AMC131M03_REG_DCDC_FREQ 0x31
        #DEFINE AMC131M03_IND_DCDC_FREQ 11
        #DEFINE AMC131M03_LEN_DCDC_FREQ 4
    //Bits 7-1 RESERVED
    //Bit 0 is subregister DCDC_EN
        #DEFINE AMC131M03_REG_DCDC_EN 0x31
        #DEFINE AMC131M03_IND_DCDC_EN 0
        #DEFINE AMC131M03_LEN_DCDC_EN 1

//Address 0x32 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x33 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x34 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x35 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x36 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x37 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x38 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x39 (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3A (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3B (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3C (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3D (REGISTER RESERVED)
//No #DEFINE for this register because it's reserved
//Define the subregisters
    //Bits 15-0 RESERVED

//Address 0x3E (REGISTER REGMAP_CRC)
#DEFINE AMC131M03_REG_REGMAP_CRC 0x3E
//Define the subregisters
    //Bits 15-0 are subregister REG_CRC
        #DEFINE AMC131M03_REG_REG_CRC 0x3E
        #DEFINE AMC131M03_IND_REG_CRC 15
        #DEFINE AMC131M03_LEN_REG_CRC 16


//End of file